apiVersion: v1
kind: ConfigMap
metadata:
  name: ris-dashboard-config
  namespace: ris-dashboard
data:
  NODE_ENV: "production"
  PORT: "3001"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  REALTIME_POLLING_INTERVAL: "30000"
  ENABLE_INCREMENTAL_UPDATES: "true"
  MAX_WEBSOCKET_CLIENTS: "1000"
  ENABLE_CHANGE_DETECTION: "true"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: ris-dashboard
data:
  redis.conf: |
    port 6379
    bind 0.0.0.0
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    tcp-keepalive 300
    timeout 0
    tcp-backlog 511
    loglevel notice
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 100
    notify-keyspace-events Ex